### PR TITLE
replaced blockcahin.info with explorer.lbry.io

### PR DESCRIPTION
**Pull request by painbank**
need to use a block explorer that works with LBC.

### CODE REVIEW

**Review by lyoshenka — CHANGES_REQUESTED** [review]
1. Instead of modifying the top-level index.html file directly, please make the appropriate changes in the [src](https://github.com/lbryio/lbc-paper-wallet/blob/master/src) directory, then use Grunt to create the compiled index.html file.

2. Your PR has a ton of whitespace-only changes, which makes it very difficult to review the actual code changes. In the future, that should go into a separate PR or commit.

**Comment by tzarebczan** [comment]
@painbank can you give this another shot based on the above comment?

**Comment by painbank** [comment]
yes, I will give it another go as I didn't use Grunt the first time.  was wondering about the whitespace problems and didn't like it overall.  hopefully sometime today.  was a busy weekend

**Comment by painbank** [comment]
closing this PR.  new PR - https://github.com/lbryio/lbc-paper-wallet/pull/5

**Pull request closed without merging**
