### PR TITLE
replaced blockcahin.info with explorer.lbry.io

### PR DESCRIPTION
**Pull request by painbank**
closing the other PR.

### CODE REVIEW

**Review by lyoshenka — CHANGES_REQUESTED** [review]
you missed a few spots in urls. do another search please. when replacing urls, make sure you're creating a url that's valid on our explorer

also, run the build script and include the compiled html file in your PR

thanks.

**Comment by painbank** [comment]
ok, not sure how to sign the html file:

index-SHA256-dc42363b780454c756ceaa1b9aa5601ea6fd1bb72300e309e63ea68241944415.html

.... running grunt resolves to
index.html

I also don't see any other references that don't have blockchain.info in them, other than the signed html file above, which should be generated.  not sure how to add the 256 hash to the html file

**Comment by tzarebczan** [comment]
@painbank looks like www.blockexplorer.com was also referenced in a bunch of translations as an alternative explorer. They may not actually be getting used anywhere, not sure.

**Comment by painbank** [comment]
@tzarebczan can you check now.  not sure what else to do now to fix this.

**Comment by tzarebczan** [comment]
Thanks @painbank . This isn't a super high priority right now as we don't even have a way to sweep paper wallets into the LBRY. We'll revisit in a few weeks.

**Pull request merged**
