### PR TITLE
Paper wallet for LBRY Credits

### PR DESCRIPTION
**Pull request by todd1251**

### CODE REVIEW

**Comment by todd1251** [comment]
Have successfully tested the generated paper wallet with `lbryum` and Coinomi.

### Paper wallet generated using `lbc-paper-wallet.html`
Address: `bZ8YVFhshYaMDYswW2ug84ddK8MMwC4pky`
Private key: `L3hrHgiCPZBw8wpaYoUg4LxjbyMDHmKEtg4UC3Uk1JUjEfigGHTP`

```
$ lbryum restore L3hrHgiCPZBw8wpaYoUg4LxjbyMDHmKEtg4UC3Uk1JUjEfigGHTP
Password (hit return if you do not wish to encrypt your wallet):
Confirm: 

$ lbryum listaddresses
[
  "bZ8YVFhshYaMDYswW2ug84ddK8MMwC4pky"
]

$ lbryum getprivatekeys bZ8YVFhshYaMDYswW2ug84ddK8MMwC4pky
WARNING: ALL your private keys are secret.
Exposing a single private key can compromise your entire wallet!
In particular, DO NOT use 'redeem private key' services proposed by third
parties.
Password:
[
  "L3hrHgiCPZBw8wpaYoUg4LxjbyMDHmKEtg4UC3Uk1JUjEfigGHTP"
]

$ lbryum getbalance
{
  "confirmed": "0"
}
```

### Send 1 LBC to bZ8YVFhshYaMDYswW2ug84ddK8MMwC4pky
https://explorer.lbry.io/tx/685bb723eec1f843158fa16ee65c32eb495b97c69bd34c6e04050d63e42c1c4e

```
$ lbryum getbalance
{
  "confirmed": "1"
}
```

### Coinomi wallet generated
Recovery passphrase: `ask affair example deal decade never snow virus ordinary bind luxury winner paddle spot boat story bean dust`

### Sweep from `bZ8YVFhshYaMDYswW2ug84ddK8MMwC4pky` to `bQHhTwcyhTcHqipPvFM8J6nSXxrNJ6i2HM` by scanning QR code of paper wallet address
https://explorer.lbry.io/tx/206944c35b072a8337faae8b6631604e33b4958a15da1c4bdc5a0390ea2e22d8

sweep

sweep-confirm

balance

```
$ lbryum getbalance
{
  "confirmed": "0"
}
```

### Send all from `bQHhTwcyhTcHqipPvFM8J6nSXxrNJ6i2HM` back to `bZ8YVFhshYaMDYswW2ug84ddK8MMwC4pky` by scanning QR code of paper wallet private key
https://explorer.lbry.io/tx/09d53b379cbbbac7d7f54f6c39456daa7453c9cc562b9e919f56a023bf170cda

address

send

**Comment by todd1251** [comment]
The standalone `lbc-paper-wallet.html` artifact needs to be hosted somewhere. Could use `github.io` but it might be preferable to be on the `lbry.io` domain?

**Comment by tzarebczan** [comment]
@todd1251 this is awesome, I'll give it a whirl today. I got your email claiming the bounty also, that will be paid once this is confirmed operational.

**Comment by tzarebczan** [comment]
@todd1251 have you messed around with the other options available in the paper wallet generator, or only tried the single wallet?

**Comment by todd1251** [comment]
@tzarebczan I tested that each wallet generation function works / doesn't crash... but only transferred real LBC using the Single Wallet function. I did test that the Wallet Details / QR codes / BIP-38 encryption is compatible with `lbryum` and Coinomi.

The only functional change to the wallet generation is the public key prefix used by `lbrycrdd`. The private key prefix is actually the same as Bitcoin in the official lbry.io client and `lbryum` (plus Coinomi expects it) even though the `lbrycrdd` source code gives a different prefix). I checked a number of lbry.io and `lbryum` generated wallets and they're all the same (prefix `0x80` not `0x1c` per `lbrycrdd` source code). 

As such, I'm reasonably confident this will be functionally equivalent to bitaddress.org.

I did disable the artistic wallet since I'm not much of a designer but that could be added back in if someone can design a fancy "note" for LBC. Otherwise it is functional as a paper wallet just no fancy graphics! ;-)

**Comment by todd1251** [comment]
Superseded by https://github.com/lbryio/lbc-paper-wallet/pull/2

**Pull request closed without merging**
